# Generated by Django 4.2.11 on 2025-05-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_video', '0011_alter_videoplayer_cmsplugin_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoplayer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='videoplayer',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='videoplayer',
            name='upload_date',
            field=models.DateField(blank=True, null=True, verbose_name='Upload Date'),
        ),
    ]
